baseURL = "https://blog.bojo.wtf/"
languageCode = "en-us"
title = "bojoism"
theme = "notepadium"

[params]
style = "auto"
slogan = "thoughts on managing software engineering teams"

[params.nav]
showCategories = true
showTags = true

[params.profile]
enable = true
github = "https://github.com/boj"
twitter = "https://twitter.com/mojobojo"
