baseURL = "https://blog.bojo.wtf/"
languageCode = "en-us"
title = "bojoism"
theme = "flat"

[params]
style = "auto"
slogan = "thoughts on life, the universe, and everything"

[params.nav]
showCategories = true
showTags = true

[[params.nav.custom]]
title = "About"
url = "/pages/about"

[params.profile]
enable = true
github = "boj"
twitter = "mojobojo"
